### ISSUE TITLE
403 Authorization exception

### ISSUE THREAD

**Issue by sagarkal** [sivasamyk/logtrail#323]
Hi,

I have bundled Logtrail 6.2.4 with Nginx latest and Kibana 6.2.4 in a docker image. When I try to run the Kibana, after authenticating successfully, I get the below error
![screenshot from 2018-10-28 18-19-56](https://user-images.githubusercontent.com/9586169/47624879-1c77ac80-dade-11e8-9d29-2dec4ad01db3.png)

In the Kibana logs, I get 

```
betademo [29/Oct/2018:01:17:07 +0000] "POST /logtrail/search HTTP/1.1" 499 0 "http://<Secret_url>/app/logtrail" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36" "-"
Error while executing search { Authorization Exception :: {"path":"/active-logs-abic-*/_search","query":{"size":500},"body":"{\"sort\":[{\"@timestamp\":{\"order\":\"asc\",\"unmapped_type\":\"boolean\"}}],\"query\":{\"bool\":{\"must\":{\"query_string\":{\"analyze_wildcard\":true,\"default_field\":\"log\",\"query\":\"*\"}},\"filter\":{\"bool\":{\"must\":[],\"must_not\":[]}}}},\"highlight\":{\"pre_tags\":[\"logtrail.highlight.pre_tag\"],\"post_tags\":[\"logtrail.highlight.post_tag\"],\"fields\":{\"log\":{\"number_of_fragments\":0}}}}","statusCode":403,"response":"{\"message\":\"'YmV0YWRlbW86U2FueWFtQDIx' not a valid key=value pair (missing equal-sign) in Authorization header: 'Basic YmV0YWRlbW86U2FueWFtQDIx'.\"}"}
    at respond (/opt/kibana/node_modules/elasticsearch/src/lib/transport.js:295:15)
    at checkRespForFailure (/opt/kibana/node_modules/elasticsearch/src/lib/transport.js:254:7)
    at HttpConnector.<anonymous> (/opt/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/opt/kibana/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  status: 403,
  displayName: 'AuthorizationException',
  message: 'Authorization Exception',
  path: '/active-logs-abic-*/_search',
  query: { size: 500 },
  body: { message: '\'YmV0YWRlbW86U2FueWFtQDIx\' not a valid key=value pair (missing equal-sign) in Authorization header: \'Basic YmV0YWRlbW86U2FueWFtQDIx\'.' },
  statusCode: 403,
  response: '{"message":"\'YmV0YWRlbW86U2FueWFtQDIx\' not a valid key=value pair (missing equal-sign) in Authorization header: \'Basic YmV0YWRlbW86U2FueWFtQDIx\'."}',
  toString: [Function],
  toJSON: [Function] }

```
My Logtrail configuration:

```
{
  "_index" : ".logtrail",
  "_type" : "config",
  "_id" : "1",
  "_version" : 39,
  "found" : true,
  "_source" : {
    "version" : 2,
    "index_patterns" : [
      {
        "es" : {
          "default_index" : "active-logs-abic-*"
        },
        "tail_interval_in_seconds" : 10,
        "es_index_time_offset_in_seconds" : 0,
        "display_timezone" : "local",
        "display_timestamp_format" : "MMM DD HH:mm:ss ZZ",
        "max_buckets" : 500,
        "default_time_range_in_days" : 0,
        "max_hosts" : 100,
        "max_events_to_keep_in_viewer" : 5000,
        "default_search" : "",
        "fields" : {
          "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp",
            "hostname" : "logtrail.host",
            "program" : "logtrail.program",
            "message" : "log"
          },
          "keyword_suffix" : ""
        },
        "color_mapping" : null
      }
    ]
  }
}
```

**Comment by sivasamyk** [comment]
@sagarkal You get this error only when you bundle logtrail with Kibana? From the logs I see there is some issue with auth settings, which is not related to logtrail.

**Comment by sagarkal** [comment]
Sorry, the problem was with the AWS managed ElasticSearch. It was yelling because the Authorization header was set. So when I removed the authorization header before Kibana connected to ElasticSearch, I no longer saw the error I mentioned above.
