### ISSUE TITLE
Support for Kibana 7.9

### ISSUE THREAD

**Issue by fpytloun** [sivasamyk/logtrail#402]
Trying to build logtrail for Kibana 7.9 but it fails with following:

```
Error in worker TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
{"type":"log","@timestamp":"2020-08-26T16:38:46Z","tags":["fatal","root"],"pid":2,"message":"{ Error: Optimizations failure.\n   555 modules\n    \n    ERROR in ./plugins/logtrail/public/app.js\n    Module not found: Error: Can't resolve 'ui/autoload/styles' in '/usr/share/kibana/plugins/logtrail/public'\n\n    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:433:26)\n    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:43:26)\n    at finalCallback (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:257:39)\n    at hooks.done.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:273:13)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:271:21)\n    at hooks.afterCompile.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:681:15)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:678:31)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at hooks.optimizeAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1423:35)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n  cause:\n   { Error: Optimizations failure.\n      555 modules\n       \n       ERROR in ./plugins/logtrail/public/app.js\n       Module not found: Error: Can't resolve 'ui/autoload/styles' in '/usr/share/kibana/plugins/logtrail/public'\n   \n       at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:433:26)\n       at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:43:26)\n       at finalCallback (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:257:39)\n       at hooks.done.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:273:13)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:271:21)\n       at hooks.afterCompile.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:681:15)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:678:31)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at hooks.optimizeAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1423:35)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n     data:\n      { errors: [Array],\n        warnings: [],\n        version: '4.41.5',\n        hash: '841f7b592fe5d022145b',\n        time: 25333,\n        builtAt: 1598459926666,\n        publicPath: '__REPLACE_WITH_PUBLIC_PATH__',\n        outputPath: '/usr/share/kibana/optimize/bundles',\n        assetsByChunkName: [Object],\n        assets: [Array],\n        filteredAssets: 0,\n        entrypoints: [Object],\n        namedChunkGroups: [Object],\n        chunks: [Array],\n        modules: [Array],\n        filteredModules: 0,\n        logging: [Object],\n        children: [Array] },\n     isBoom: true,\n     isServer: true,\n     output: { statusCode: 500, payload: [Object], headers: {} },\n     reformat: [Function],\n     typeof: [Function: internal] },\n  isOperational: true,\n  data:\n   { errors:\n      [ './plugins/logtrail/public/app.js\\nModule not found: Error: Can\\'t resolve \\'ui/autoload/styles\\' in \\'/usr/share/kibana/plugins/logtrail/public\\'\\nresolve \\'ui/autoload/styles\\' in \\'/usr/share/kibana/plugins/logtrail/public\\'\\n  Parsed request is a module\\n  using description file: /usr/share/kibana/plugins/logtrail/package.json (relative path: ./public)\\n    aliased with mapping \\'ui\\': \\'/usr/share/kibana/src/legacy/ui/public\\' to \\'/usr/share/kibana/src/legacy/ui/public/autoload/styles\\'\\n      using description file: /usr/share/kibana/plugins/logtrail/package.json (relative path: ./public)\\n        Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n        using description file: /usr/share/kibana/package.json (relative path: ./src/legacy/ui/public/autoload/styles)\\n          no extension\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/autoload/styles doesn\\'t exist\\n          .js\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/autoload/styles.js doesn\\'t exist\\n          .ts\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/autoload/styles.ts doesn\\'t exist\\n          .tsx\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/autoload/styles.tsx doesn\\'t exist\\n          .json\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/autoload/styles.json doesn\\'t exist\\n          as directory\\n            /usr/share/kibana/src/legacy/ui/public/autoload/styles doesn\\'t exist\\n[/usr/share/kibana/src/legacy/ui/public/autoload/styles]\\n[/usr/share/kibana/src/legacy/ui/public/autoload/styles.js]\\n[/usr/share/kibana/src/legacy/ui/public/autoload/styles.ts]\\n[/usr/share/kibana/src/legacy/ui/public/autoload/styles.tsx]\\n[/usr/share/kibana/src/legacy/ui/public/autoload/styles.json]\\n @ ./plugins/logtrail/public/app.js 10:0-28\\n @ ./optimize/bundles/logtrail.entry.js' ],\n     warnings: [],\n     version: '4.41.5',\n     hash: '841f7b592fe5d022145b',\n     time: 25333,\n     builtAt: 1598459926666,\n     publicPath: '__REPLACE_WITH_PUBLIC_PATH__',\n     outputPath: '/usr/share/kibana/optimize/bundles',\n     assetsByChunkName:\n      { dark_theme: [Array],\n        light_theme: [Array],\n        logtrail: [Array],\n        status_page: 'status_page.bundle.js',\n        timelion: 'timelion.bundle.js' },\n     assets:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object] ],\n     filteredAssets: 0,\n     entrypoints:\n      { logtrail: [Object],\n        status_page: [Object],\n        timelion: [Object],\n        light_theme: [Object],\n        dark_theme: [Object] },\n     namedChunkGroups:\n      { logtrail: [Object],\n        status_page: [Object],\n        timelion: [Object],\n        light_theme: [Object],\n        dark_theme: [Object] },\n     chunks:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object] ],\n     modules:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        ... 455 more items ],\n     filteredModules: 0,\n     logging: { 'webpack.buildChunkGraph.visitModules': [Object] },\n     children: [ [Object], [Object], [Object] ] },\n  isBoom: true,\n  isServer: true,\n  output:\n   { statusCode: 500,\n     payload:\n      { statusCode: 500,\n        error: 'Internal Server Error',\n        message: 'An internal server error occurred' },\n     headers: {} },\n  reformat: [Function],\n  typeof: [Function: internal] }"}
 FATAL  Error: Optimizations failure.
   555 modules
    
    ERROR in ./plugins/logtrail/public/app.js
    Module not found: Error: Can't resolve 'ui/autoload/styles' in '/usr/share/kibana/plugins/logtrail/public'
```

**Comment by sivasamyk** [comment]
Added support for 7.9.0 and 7.9.1 - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.9.0-0.1.31.zip and https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.9.1-0.1.31.zip
